### ISSUE TITLE
AEIP-21: Mining use genesis pool

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#1243]
To leverage AEIP21, the transaction's validation process have to updated including

```[tasklist]
### Tasks
- [ ] https://github.com/archethic-foundation/archethic-node/issues/1405
- [ ] https://github.com/archethic-foundation/archethic-node/issues/1406
- [ ] https://github.com/archethic-foundation/archethic-node/issues/1407
- [ ] https://github.com/archethic-foundation/archethic-node/issues/1408
```
