### ISSUE TITLE
AEIP-21: Update APIs and Explorer with new behavior

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#1245]
```[tasklist]
### Tasks
- [ ] https://github.com/archethic-foundation/archethic-node/issues/1410
- [ ] https://github.com/archethic-foundation/archethic-node/issues/1411
- [ ] https://github.com/archethic-foundation/archethic-node/issues/1412
```
