### ISSUE TITLE
Support of aggregate signatures

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#1518]
### Describe the area

Coming from the [AEIP-24](https://github.com/archethic-foundation/aeip/blob/main/AEIP-24.md), to have a secure and cost efficient transaction's consensus and trust, we have to implement aggregated signature into transaction and mining.

We could divide this implementation into subtasks:

- [ ] Support BLS signature scheme
- [ ] Update node's transaction to support BLS's public key publication
- [ ] Leverage BLS aggregated signatures for cross validation stamps
- [ ] Leverage BLS aggregated signatures for replication's signatures
- [ ] Update the transaction's structure to include the aggregated signatures from replication nodes and cross validation nodes
