### ISSUE TITLE
Improve performance of the BeaconChain explorer

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#291]
### What happened?

When we go the BeaconChain explorer http://localhost:4000/explorer/chain/beacon, the initial rendering is quite long after fetch of the transaction chain.
We have a blank screen for 1-3 seconds and then the UI displays the list.

### What is expected ?

Rendering should be as fast as possible, even asynchronous by updates if it's required.
We also need to check if the subscriptions is not causing any slowdown

### Tasks 

- [x] Investigate the possible bottlenecks 
- In the investigation I found out that there is duplication of transaction.
- The p2p message for returning the tx's in slot contents is not working and the page 1 is empty even though there are tx's 
- [x] Imporve the bottlenecks with some async or other possible mechanisms
- Efficient way to fetch unsealed(unsummarized) beacon transactions.
 In subset, transaction attestations the slot is empty due to which async msg is not being sent to the node
 But subscribed nodes are being broadcasted the tx when it occurs and it is being added to the slot 
- [x] Need clearity on current slot with empty transaction_attestations list transactions by date from tx chain
- Efficent way to fetch tx's with BeaconSummaries{} Msg

## PR

- #339 
- #360

**Comment by apoorv-2204** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/291?planning-poker) with ZenHub @blackode

**Comment by apoorv-2204** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/291?planning-poker) with ZenHub @Neylix

**Comment by AmodD** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/291?planning-poker) with ZenHub @imnik11
